POST http://localhost:8080/home
Content-Type: application/json

{
  "name": "fwwwd",
  "email": "java001@gmail.com",
  "age": 18
}

###

POST http://localhost:8080/account/1/5f1e7f92-ab28-4c16-882b-ef6283bdeddb/deposit?amount=100.00
Content-Type: application/json



###
GET http://localhost:8080/account/1